"""FastFHIR Generator — cross-language Python-binding stubs.

Relocated from ffc.py lines 1729-2007.  These emit per-resource ``.py``,
``.pyi`` fields modules, AST path builders, and the PEP 561 ``py.typed``
marker.  All functions write their output via ``with open`` directly.
"""

import os

from generator.emit.header import auto_header


def emit_python_fields(python_resource_map, output_dir="generated_src"):
    target_dir = os.path.join(output_dir, "python", "fields")
    os.makedirs(target_dir, exist_ok=True)

    for class_name, fields in python_resource_map.items():
        file_name = f"{class_name.lower()}.py"
        file_path = os.path.join(target_dir, file_name)
        with open(file_path, "w") as f:
            f.write("# Auto-generated by FastFHIR pipeline. Do not edit.\n")
            f.write("from .. import _core\n\n")
            f.write(f"class {class_name}:\n")
            if not fields:
                f.write("    pass\n\n")
                continue
            for field_name, metadata in fields.items():
                idx, orig_name, owner, fhir_type = metadata
                safe_name = field_name.upper()
                if safe_name in {"CLASS", "IMPORT", "GLOBAL", "FOR", "WHILE", "IN", "IS", "AS"}:
                    safe_name += "_"
                if fhir_type in ("Resource", "DomainResource"):
                    f.write("    # Polymorphic Wrapper Bridge (Auto-Hops to Payload)\n")
                f.write(f'    {safe_name} = _core.Field({idx}, "{orig_name}", "{owner}")\n')

    print(f"-- Emitted {len(python_resource_map)} Python field modules into: {target_dir}/")


def emit_python_ast(master_blocks, block_key_defs, token_registry, output_dir="generated_src"):
    target_dir = os.path.join(output_dir, "python", "fields")
    os.makedirs(target_dir, exist_ok=True)

    with open(os.path.join(target_dir, "base.py"), "w") as f:
        f.write("class ASTNode:\n")
        f.write("    def __init__(self, current_path=None):\n")
        f.write("        self.path = current_path or tuple()\n")
        f.write("    def cast(self, target_class):\n")
        f.write("        if isinstance(target_class, ASTNode):\n")
        f.write("            return type(target_class)(self.path)\n")
        f.write("        return target_class(self.path)\n\n")
        f.write("class ASTArrayNode(ASTNode):\n")
        f.write("    def __init__(self, current_path, item_class):\n")
        f.write("        super().__init__(current_path)\n")
        f.write("        self.item_class = item_class\n")
        f.write("    def __getitem__(self, index):\n")
        f.write("        if isinstance(index, int):\n")
        f.write("            return self.item_class(self.path + (index,))\n")
        f.write(
            "        raise TypeError('FastFHIR: Only integer indexing is allowed for arrays.')\n"
        )

    for path, layout in block_key_defs:
        class_name = path.replace(".", "_").upper()
        file_name = f"{class_name.lower()}.py"
        with open(os.path.join(target_dir, file_name), "a") as f:
            f.write("from .base import ASTNode\n")
            f.write(f"\nclass {class_name}_PATH(ASTNode):\n")
            if not layout:
                f.write("    pass\n")
            for f_def in layout:
                orig_name = f_def["orig_name"]
                token_id, ns_name = token_registry[path][orig_name]
                safe_name = orig_name.upper()
                if safe_name in {"CLASS", "IMPORT", "GLOBAL", "FOR", "WHILE", "IN", "IS", "AS"}:
                    safe_name += "_"
                f.write("    @property\n")
                is_arr = f_def.get("is_array", False)
                if is_arr:
                    f.write(f"    def {safe_name}(self):\n")
                    f.write(
                        f"        return ASTArrayNode(self.path + ({token_id},), self.item_class)\n"
                    )
                else:
                    f.write(f"    def {safe_name}(self):\n")
                    f.write(f"        return ASTNode(self.path + ({token_id},))\n")


def emit_python_fields_stubs(python_resource_map, output_dir="generated_src"):
    target_dir = os.path.join(output_dir, "python", "fields")
    os.makedirs(target_dir, exist_ok=True)
    for class_name, fields in python_resource_map.items():
        file_path = os.path.join(target_dir, f"{class_name.lower()}.pyi")
        with open(file_path, "w") as f:
            f.write("# Auto-generated stub for type checking.\n")
            f.write("from .. import _core\n\n")
            f.write(f"class {class_name}:\n")
            for field_name, metadata in fields.items():
                idx, orig_name, owner, _fhir_type = metadata
                safe_name = field_name.upper()
                if safe_name in {"CLASS", "IMPORT", "GLOBAL", "FOR", "WHILE", "IN", "IS", "AS"}:
                    safe_name += "_"
                f.write(f"    {safe_name}: _core.Field\n")
            if not fields:
                f.write("    pass\n")
            f.write("\n")


def emit_python_ast_stubs(master_blocks, block_key_defs, output_dir="generated_src"):
    target_dir = os.path.join(output_dir, "python", "fields")
    with open(os.path.join(target_dir, "base.pyi"), "w") as f:
        f.write("# Auto-generated stub file for type checking.\n")
        f.write("from typing import Tuple, Type, TypeVar, Generic, overload\n\n")
        f.write("T = TypeVar('T', bound='ASTNode')\n\n")
        f.write("class ASTNode:\n")
        f.write("    path: Tuple\n")
        f.write("    def __init__(self, current_path: Tuple | None = ...) -> None: ...\n")
        f.write("    def cast(self, target_class: Type[T] | ASTNode) -> T: ...\n\n")
        f.write("class ASTArrayNode(ASTNode):\n")
        f.write("    item_class: Type[ASTNode]\n")
        f.write(
            "    def __init__(self, current_path: Tuple, item_class: Type[ASTNode]) -> None: ...\n"
        )
        f.write("    def __getitem__(self, index: int) -> ASTNode: ...\n\n")
    for path, layout in block_key_defs:
        class_name = path.replace(".", "_").upper()
        stub_path = os.path.join(target_dir, f"{class_name.lower()}.pyi")
        with open(stub_path, "w") as f:
            f.write("# Auto-generated stub file for type checking.\n")
            f.write("from typing import overload\n")
            f.write("from . import _core\n")
            f.write("from .base import ASTNode, ASTArrayNode\n\n")
            f.write(f"class {class_name}_PATH(ASTNode):\n")
            if not layout:
                f.write("    ...\n")
            for f_def in layout:
                orig_name = f_def["orig_name"]
                safe_name = orig_name.upper()
                if safe_name in {"CLASS", "IMPORT", "GLOBAL", "FOR", "WHILE", "IN", "IS", "AS"}:
                    safe_name += "_"
                is_array = f_def.get("is_array", False)
                if f_def["fhir_type"] in master_blocks:
                    target_path = f_def["fhir_type"]
                    base_name = target_path.replace(".", "_").upper()
                    return_type = f"{base_name}_PATH"
                    if is_array:
                        return_type = "ASTArrayNode"
                else:
                    return_type = "ASTNode"
                    if is_array:
                        return_type = "ASTArrayNode"
                f.write("    @property\n")
                f.write(f"    def {safe_name}(self) -> {return_type}: ...\n")
            f.write("\n")


def emit_py_typed_marker(output_dir="generated_src"):
    py_typed_path = os.path.join(output_dir, "python", "py.typed")
    os.makedirs(os.path.dirname(py_typed_path), exist_ok=True)
    with open(py_typed_path, "w") as f:
        pass
    print(f"-- Emitted py.typed marker file: {py_typed_path}")


def emit_python_fields_init(
    python_resource_map: dict[str, dict[str, tuple]], output_dir: str = "generated_src"
) -> None:
    """Emit fields/__init__.py re-exporting every resource field schema.

    Without a real package init the generated per-resource modules form a PEP 420
    namespace package, so `from fastfhir.fields import Patient` fails (TASKS.md A21)
    for both the staged build-tree package and the installed one. Called after
    emit_python_ast so base.py is written in the same run.
    """
    target_dir = os.path.join(output_dir, "python", "fields")
    os.makedirs(target_dir, exist_ok=True)
    class_names = sorted(python_resource_map.keys())
    lines = [
        "# Auto-generated by FastFHIR pipeline. Do not edit.",
        '"""Generated per-resource field schemas."""',
        "",
        "from .base import ASTNode, ASTArrayNode",
        "",
    ]
    lines += [f"from .{name.lower()} import {name}" for name in class_names]
    lines += ["", "__all__ = ["]
    lines += [f'    "{name}",' for name in class_names]
    lines += ['    "ASTNode",', '    "ASTArrayNode",', "]"]
    with open(os.path.join(target_dir, "__init__.py"), "w") as f:
        f.write("\n".join(lines) + "\n")
