# =====================================================================
# FastFHIR Dictionary Generator (ffd.py)
# 
# Scans FHIR ValueSet bundles to extract allowed values,
# and generates FF_{version}_Dictionary.hpp with enum classes + parse/serialize
# helpers for each bounded code system.
#
# Author: Ryan Landvater (ryanlandvater[at]gmail[dot]com)
# Copyright (c) 2025 Ryan Landvater. All rights reserved.
# License: FastFHIR Shared Source License (FF-SSL)
# =============================================================


import os
import json
import re
import hashlib

# ─── SHA-256 truncated hash for stable dictionary code assignment ───────
# These constants MUST match the values in include/FF_Primitives.hpp.
_FF_CODE_NULL = 0xFFFFFFFF

def _code_hash(s: str) -> int:
    """Return a deterministic 31-bit positive uint32_t for `s`.

    Same string → same code always, regardless of ValueSet ordering.
    A code string that hashes to FF_CODE_NULL is remapped to 1.
    """
    h = hashlib.sha256(s.encode()).digest()
    val = int.from_bytes(h[:4], 'little') & 0x7FFFFFFF  # 31-bit, always positive
    return 1 if val == _FF_CODE_NULL else val


# ─── RECOVERY TAG PARSER (reads the permanent include/FF_Recovery.hpp) ──
def _parse_recovery_tags(recovery_path="include/FF_Recovery.hpp"):
    """Parse the hand-maintained RECOVERY_TAG enum and return {name: value}."""
    tags = {}
    with open(recovery_path, "r") as f:
        for line in f:
            m = re.match(r'\s+(\w+)\s*=\s*(0x[0-9A-Fa-f]+)', line)
            if m:
                tags[m.group(1)] = int(m.group(2), 16)
    return tags



def _version_sort_key(label):
    m = re.match(r'^R(\d+)([A-Za-z]*)$', label)
    if not m:
        return (10**9, label)
    major = int(m.group(1))
    minor = m.group(2).upper()
    return (major, minor)


# Map of special characters to descriptive names for enum generation
SYMBOL_MAP = {
    '%': 'PERCENT',
    '/': 'PER',
    '<=': 'LESS_OR_EQUAL',
    '>=': 'GREATER_OR_EQUAL',
    '<': 'LESS_THAN',
    '>': 'GREATER_THAN',
    '=': 'EQUAL',
    '+': 'PLUS',
    '-': 'MINUS',
    '*': 'STAR',
    '@': 'AT',
    '#': 'HASH',
    '&': 'AND'
}
def _sanitize_identifier(raw, prefix="", is_uri=False):
    token = raw
    if not is_uri:
        for sym, word in SYMBOL_MAP.items():
            token = token.replace(sym, f"_{word}_")
    token = re.sub(r'[^A-Za-z0-9_]', '_', token.upper())
    token = re.sub(r'_+', '_', token).strip('_')
    if not token:
        token = "EMPTY"
    if token[0].isdigit():
        token = "N_" + token
    return f"{prefix}{token}"

def generate_fastfhir_dictionary(v_name, input_dir="fhir_specs", output_dir="generated_src"):
    bundle_path = os.path.join(input_dir, v_name, "valuesets.json")
    if not os.path.exists(bundle_path):
        print(f"[Warning] Missing: {bundle_path}")
        return False

    with open(bundle_path, 'r', encoding='utf-8') as f:
        bundle = json.load(f)

    seen_enums = set()
    mappings = [] 
    entries = bundle.get('entry', [])
    for entry in entries:
        vs = entry.get('resource', {})
        if vs.get('resourceType') != 'ValueSet': continue
        
        includes = vs.get('compose', {}).get('include', [])
        for inc in includes:
            system = inc.get('system', '')
            if system and system not in seen_enums:
                # Flag as URI to bypass symbol translation ---
                clean_sys = _sanitize_identifier(system.split('/')[-1], prefix="", is_uri=True)
                enum_name = f"FF_{v_name}_URI_{clean_sys}"
                
                if enum_name in seen_enums:
                    enum_name += f"_{len(mappings) + 1}"
                mappings.append((system, enum_name))
                seen_enums.add(system)
                seen_enums.add(enum_name)

            for concept in inc.get('concept', []):
                code = concept.get('code', '')
                if code and code not in seen_enums:
                    # Flag as a Code (default) ---
                    clean_code = _sanitize_identifier(code, prefix="", is_uri=False)
                    enum_name = f"FF_{v_name}_CODE_{clean_code}"
                    
                    if enum_name in seen_enums: enum_name += f"_{len(seen_enums)}"
                    mappings.append((code, enum_name))
                    seen_enums.add(code)
                    seen_enums.add(enum_name)

    auto_header = (
        "// ============================================================\n"
        "// This file is autogenerated by FastFHIR. DO NOT EDIT.\n"
        "// Copyright (c) Ryan Landvater. All rights reserved.\n"
        "// ============================================================\n"
    )

    # Stabilize output regardless of source bundle entry order.
    mappings = sorted(mappings, key=lambda x: x[0])

    # Assign hash-based codes (stable across spec ordering changes)
    code_assignments = [(raw, enum, _code_hash(raw)) for raw, enum in mappings]

    # Collision check: fail loudly if two codes map to the same value
    seen = {}
    for raw, enum, val in code_assignments:
        if val in seen:
            raise RuntimeError(
                f"Dictionary code collision: '{raw}' ({enum}) and "
                f"'{seen[val]}' both hash to 0x{val:08X}"
            )
        seen[val] = raw

    # Content generation logic
    hpp =  f"{auto_header}// Generated from {v_name} ValueSets\n#pragma once\n#include \"../include/FF_Primitives.hpp\"\n\n"
    hpp += f"enum FF_{v_name}_Code : uint32_t {{\n    FF_{v_name}_NULL = FF_CODE_NULL,\n"
    for raw, enum, val in code_assignments: hpp += f"    {enum:<40} = 0x{val:08X},\n"
    hpp += f"}};\n\nFF_EXPORT const char* FF_{v_name}_Resolve(FF_{v_name}_Code code);\nFF_EXPORT uint32_t FF_{v_name}_GetCode(const std::string& str);\n"
    
    cpp = f"{auto_header}#include \"FF_{v_name}_Dictionary.hpp\"\n#include <unordered_map>\n\n"
    cpp += f"const char* FF_{v_name}_Resolve(FF_{v_name}_Code code) {{\n"
    cpp += f"    static const std::unordered_map<uint32_t, const char*> REV = {{\n"
    for raw, enum, val in code_assignments: cpp += f"        {{0x{val:08X}, \"{raw}\"}},\n"
    cpp += f"    }}; auto it = REV.find(static_cast<uint32_t>(code));\n"
    cpp += f"    return it != REV.end() ? it->second : \"\";\n}}\n\n"
    cpp += f"uint32_t FF_{v_name}_GetCode(const std::string& str) {{\n"
    cpp += f"    static const std::unordered_map<std::string, uint32_t> MAP = {{\n"
    for raw, enum, val in code_assignments: cpp += f"        {{\"{raw}\", 0x{val:08X}}},\n"
    cpp += f"    }}; auto it = MAP.find(str); return it != MAP.end() ? it->second : FF_CODE_NULL;\n}}\n"

    # Write to generated_src/
    os.makedirs(output_dir, exist_ok=True)
    with open(os.path.join(output_dir, f"FF_{v_name}_Dictionary.hpp"), "w") as f: f.write(hpp)
    with open(os.path.join(output_dir, f"FF_{v_name}_Dictionary.cpp"), "w") as f: f.write(cpp)
    return True

def _normalize_version_configs(versions, default_input_dir):
    normalized = []
    for item in versions:
        if isinstance(item, str):
            normalized.append((item, os.path.join(default_input_dir, item)))
        elif isinstance(item, (tuple, list)) and len(item) == 2:
            v_name, version_dir = item
            if isinstance(v_name, str) and isinstance(version_dir, str):
                normalized.append((v_name, version_dir))
            else:
                print(f"[Warning] Skipping invalid version config: {item}")
        else:
            print(f"[Warning] Skipping invalid version config: {item}")
    return normalized

def generate_master_dictionary(versions, input_dir="fhir_specs", output_dir="generated_src"):
    os.makedirs(output_dir, exist_ok=True)
    normalized_versions = _normalize_version_configs(versions, input_dir)
    normalized_versions = sorted(normalized_versions, key=lambda x: _version_sort_key(x[0]))

    active_versions = []
    for v_name, version_dir in normalized_versions:
        version_parent = os.path.dirname(version_dir) if os.path.dirname(version_dir) else "."
        version_leaf = os.path.basename(version_dir)
        if generate_fastfhir_dictionary(version_leaf, version_parent, output_dir):
            active_versions.append(v_name)

    auto_header = (
        "// ============================================================\n"
        "// This file is autogenerated by FastFHIR. DO NOT EDIT.\n"
        "// Copyright (c) Ryan Landvater. All rights reserved.\n"
        "// ============================================================\n"
    )

    # Master Header logic
    hpp = f"{auto_header}#pragma once\n#include \"../include/FF_Primitives.hpp\"\n"
    for v in active_versions: hpp += f"#include \"FF_{v}_Dictionary.hpp\"\n"
    
    hpp += "\ninline const char* FF_ResolveCode(uint32_t code, uint32_t version) {\n    if (code & FF_CUSTOM_STRING_FLAG) return nullptr;\n"
    for i, v in enumerate(reversed(active_versions)):
        prefix = "if" if i == 0 else "else if"
        hpp += f"    {prefix} (version >= FHIR_VERSION_{v}) return FF_{v}_Resolve(static_cast<FF_{v}_Code>(code));\n"
    hpp += "    return \"\";\n}\n\ninline uint32_t FF_GetDictionaryCode(const std::string& str, uint32_t version) {\n"
    for i, v in enumerate(reversed(active_versions)):
        prefix = "if" if i == 0 else "else if"
        hpp += f"    {prefix} (version >= FHIR_VERSION_{v}) return FF_{v}_GetCode(str);\n"
    hpp += "    return 0;\n}\n"

    with open(os.path.join(output_dir, "FF_Dictionary.hpp"), "w") as f: f.write(hpp)
    print(f"[Success] Master Dictionary written to {output_dir}/FF_Dictionary.hpp")