"""FastFHIR Generator — WASM extension codec emitter.

Relocated from ffc.py lines 2358-2585.  For each extension StructureDefinition,
emits a self-contained C source file compilable to a .wasm codec module.

The emitted file uses:
  - Only fixed-size stack structs (no std::vector, no std::string).
  - Direct LOAD_U*/STORE_U* macros against the staging buffer pointer.
  - Three exported functions: ext_size / ext_encode / ext_decode.
"""

import os
import re

from generator.emit.header import write_if_changed

# Maximum number of fields supported in the stack-only staging layout.
_WASM_MAX_FIELDS = 64

# WASM-safe C type mapping (no heap allocation).
_WASM_CTYPE: dict[str, tuple[str, int, str]] = {
    "boolean": ("uint8_t", 1, "uint8"),
    "integer": ("uint32_t", 4, "uint32"),
    "unsignedInt": ("uint32_t", 4, "uint32"),
    "positiveInt": ("uint32_t", 4, "uint32"),
    "integer64": ("uint64_t", 8, "uint64"),
    "decimal": ("double", 8, "f64"),
}

_WASM_MAX_STRING_BYTES = 512


def _wasm_field_ctype(fhir_type: str) -> tuple[str, int]:
    """Return (c_type_str, byte_size) for a WASM-staging-compatible field type."""
    if fhir_type in _WASM_CTYPE:
        ct, sz, _ = _WASM_CTYPE[fhir_type]
        return ct, sz
    # Strings, codes, all reference types → fixed char array
    return "char", _WASM_MAX_STRING_BYTES


def emit_wasm_codec(ext_url: str, master_blocks: dict, ext_path: str, output_dir: str) -> None:
    """Emit a WASM codec .c file for the Extension at @p ext_path."""
    if ext_path not in master_blocks:
        return

    blk = master_blocks[ext_path]
    layout = blk["layout"]
    safe_name = re.sub(r"[^A-Za-z0-9]", "_", ext_url.rstrip("/").split("/")[-1])
    if not safe_name:
        safe_name = "extension"

    # ── Staging payload struct ────────────────────────────────────────────
    struct_lines = ["typedef struct {"]
    for f in layout[:_WASM_MAX_FIELDS]:
        ctype, sz = _wasm_field_ctype(f["fhir_type"])
        if sz == _WASM_MAX_STRING_BYTES:
            struct_lines.append(f'    {ctype} {f["cpp_name"]}[{sz}];')
        else:
            struct_lines.append(f"    {ctype} {f['cpp_name']};")
    struct_lines.append(f"}} {safe_name}_payload_t;")
    payload_struct = "\n".join(struct_lines)

    vtable_total = blk.get("sizes", {})
    if vtable_total:
        vtable_size = max(vtable_total.values())
    else:
        vtable_size = (layout[-1]["offset"] + layout[-1]["size"]) if layout else 10

    c_src = (
        "// =================================================================\n"
        f"// FastFHIR WASM Extension Codec — {ext_url}\n"
        "// AUTO-GENERATED by the FastFHIR generator. DO NOT EDIT.\n"
        "// Compile:\n"
        "//   wasi-sdk clang --target=wasm32-wasi -O3 -fno-exceptions\n"
        "//     -fno-rtti -nostdlib++ -Wl,--no-entry \\\n"
        f"//     -o {safe_name}.wasm {safe_name}_codec.c\n"
        "// =================================================================\n"
        "#include <stdint.h>\n"
        "#include <string.h>\n\n"
        "// ── Load/store helpers (little-endian, WASM native) ──────────────\n"
        "static inline uint8_t  ld_u8 (const uint8_t* p) { return *p; }\n"
        "static inline uint16_t ld_u16(const uint8_t* p) { uint16_t v; memcpy(&v,p,2); return v; }\n"
        "static inline uint32_t ld_u32(const uint8_t* p) { uint32_t v; memcpy(&v,p,4); return v; }\n"
        "static inline uint64_t ld_u64(const uint8_t* p) { uint64_t v; memcpy(&v,p,8); return v; }\n"
        "static inline void st_u8 (uint8_t* p, uint8_t  v) { *p = v; }\n"
        "static inline void st_u16(uint8_t* p, uint16_t v) { memcpy(p,&v,2); }\n"
        "static inline void st_u32(uint8_t* p, uint32_t v) { memcpy(p,&v,4); }\n"
        "static inline void st_u64(uint8_t* p, uint64_t v) { memcpy(p,&v,8); }\n\n"
        f"#define VTABLE_SIZE {vtable_size}u\n\n"
        f"{payload_struct}\n\n"
        "// ── ext_size ─────────────────────────────────────────────────────\n"
        '__attribute__((export_name("ext_size")))\n'
        "uint32_t ext_size(uint32_t staging_ptr, uint32_t version) {\n"
        "    (void)version;\n"
        "    (void)staging_ptr;\n"
        "    return VTABLE_SIZE;\n"
        "}\n\n"
        "// ── ext_encode ───────────────────────────────────────────────────\n"
        '__attribute__((export_name("ext_encode")))\n'
        "uint32_t ext_encode(uint32_t staging_ptr, uint32_t dest_ptr, uint32_t version) {\n"
        f"    {safe_name}_payload_t* p = ({safe_name}_payload_t*)staging_ptr;\n"
        "    uint8_t* dst = (uint8_t*)dest_ptr;\n"
        "    (void)version;\n"
    )
    # Emit per-field STORE_* calls for every field in the payload struct.
    for f in layout[:_WASM_MAX_FIELDS]:
        ctype, sz = _wasm_field_ctype(f["fhir_type"])
        cpp_name = f["cpp_name"]
        # Strings: memcpy the fixed char[].
        if sz == _WASM_MAX_STRING_BYTES:
            c_src += f"    memcpy(dst, p->{cpp_name}, {sz}); dst += {sz};\n"
        elif sz == 1:
            c_src += f"    st_u8(dst, p->{cpp_name}); dst += 1;\n"
        elif sz == 2:
            c_src += f"    st_u16(dst, p->{cpp_name}); dst += 2;\n"
        elif sz == 4:
            c_src += f"    st_u32(dst, p->{cpp_name}); dst += 4;\n"
        elif sz == 8:
            c_src += f"    st_u64(dst, p->{cpp_name}); dst += 8;\n"
    c_src += (
        "    return VTABLE_SIZE;\n"
        "}\n\n"
        "// ── ext_decode ───────────────────────────────────────────────────\n"
        '__attribute__((export_name("ext_decode")))\n'
        "void ext_decode(uint32_t src_ptr, uint32_t staging_ptr, uint32_t version) {\n"
        f"    {safe_name}_payload_t* p = ({safe_name}_payload_t*)staging_ptr;\n"
        "    const uint8_t* src = (const uint8_t*)src_ptr;\n"
        "    (void)version;\n"
    )
    for f in layout[:_WASM_MAX_FIELDS]:
        ctype, sz = _wasm_field_ctype(f["fhir_type"])
        cpp_name = f["cpp_name"]
        if sz == _WASM_MAX_STRING_BYTES:
            c_src += f"    memcpy(p->{cpp_name}, src, {sz}); src += {sz};\n"
        elif sz == 1:
            c_src += f"    p->{cpp_name} = ld_u8(src); src += 1;\n"
        elif sz == 2:
            c_src += f"    p->{cpp_name} = ld_u16(src); src += 2;\n"
        elif sz == 4:
            c_src += f"    p->{cpp_name} = ld_u32(src); src += 4;\n"
        elif sz == 8:
            c_src += f"    p->{cpp_name} = ld_u64(src); src += 8;\n"
    c_src += "}\n"

    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, f"{safe_name}_codec.c")
    write_if_changed(out_path, c_src)
    print(f"-- Emitted WASM codec: {out_path}")
