# ============================================================
# FastFHIR Generator — shared emit helpers
#
# Single source of truth for the two helpers that were previously
# DUPLICATED verbatim in tools/generator/ffc.py and make_lib.py
# (style violation SV-1 in generator_refactor_plan.md).
#
# `auto_header` and `write_if_changed` are byte-for-byte identical to
# the originals so generated wire constants stay unchanged.
#
# Author: Ryan Landvater (ryanlandvater[at]gmail[dot]com)
# Copyright (c) 2025 Ryan Landvater. All rights reserved.
# License: FastFHIR Shared Source License (FF-SSL)
# ============================================================

import os


def write_if_changed(path: str, content: str, encoding: str = "utf-8") -> None:
    """Write `content` to `path` only when the content has actually changed.

    Skipping the write preserves the file's mtime so the C++ build system
    does not consider dependent translation units stale on a no-op
    regeneration. Logic is verbatim from the original `_write_if_changed`.
    """
    if os.path.exists(path):
        try:
            with open(path, "r", encoding=encoding) as fh:
                if fh.read() == content:
                    return
        except OSError:
            pass
    with open(path, "w", encoding=encoding) as fh:
        fh.write(content)


# Emitted as the first lines of every generated C++/C file. This banner is
# wire-visible text — reproduce it character-for-character (4 lines, exact
# spacing) so generated files stay consistent with the existing tree.
auto_header = (
    "// ============================================================\n"
    "// This file is autogenerated by FastFHIR. DO NOT EDIT.\n"
    "// Copyright (c) Ryan Landvater. All rights reserved.\n"
    "// ============================================================\n"
)
