/**
 * @file FF_Builder.hpp
 * @author Ryan Landvater (ryanlandvater[at]gmail[dot]com)
 * @brief Concurrent lock-free FastFHIR stream builder.
 * @version 0.1
 * @date 2026-03-18
 * @copyright Copyright (c) 2026 Ryan Landvater. All rights reserved.
 * @license FastFHIR Shared Source License (FF-SSL) — see LICENSE file in the project root for terms.
 */
#pragma once

#include "FF_Utilities.hpp"
#include <atomic>
#include <stdexcept>
#include <string_view>
#include <functional>

namespace FastFHIR {

class Node; // Forward declaration — full definition in FF_Parser.hpp

// =====================================================================
// TYPE TRAITS (Auto-generated by ffc.py)
// =====================================================================
/**
 * @brief Maps C++ structs to their generated FastFHIR size and store functions.
 */
template<typename T> struct TypeTraits;

// =====================================================================
// PROXIES & HANDLES
// =====================================================================
class Builder;
class ObjectHandle;
struct PointerRef {
    Offset object_offset = FF_NULL_OFFSET;
    size_t field_vtable_offset = 0;
    RECOVERY_TAG target_recovery = FF_RECOVER_UNDEFINED;
};

/**
 * @brief Ephemeral proxy object returned by ObjectHandle::operator[].
 * Allows assigning either an existing Offset or dynamically appending new data.
 */
class PointerPatchProxy {
    Builder* m_builder;
    PointerRef m_ref;

public:
    PointerPatchProxy(Builder* builder, PointerRef ref) : m_builder(builder), m_ref(ref) {}

    // Option A: Assign an existing handle for data already in the stream (with strict type checking)
    PointerPatchProxy& operator=(const ObjectHandle& child);

    // Option B: Concurrently append NEW data to the stream 
    // and patch the pointer simultaneously!
    template <typename T_Data>
    Offset operator=(const T_Data& data);

    // Array indexer (Dereferences the vtable pointer to find the entry object)
    ObjectHandle operator[](size_t index) const;
};

// =====================================================================
// OBJECT HANDLE (Thread-Local Data Blocks Abstraction)
// =====================================================================
/**
 * @brief Thread-local handle representing a specific parent object being built.
 * Replaces the unsafe global operator[] on the Builder itself.
 */
class ObjectHandle {
    Builder* m_builder;
    Offset          m_offset;
    RECOVERY_TAG    m_recovery;

public:
    ObjectHandle(Builder* builder, Offset offset, RECOVERY_TAG recovery = FF_RECOVER_UNDEFINED) 
        : m_builder(builder), m_offset(offset), m_recovery(recovery) {
            if (offset != FF_NULL_OFFSET && recovery == FF_RECOVER_UNDEFINED) 
            throw std::invalid_argument("FastFHIR: Cannot instantiate an ObjectHandle with valid offset but with an UNDEFINED recovery tag.");
        }

    Offset offset() const { return m_offset; }
    RECOVERY_TAG recovery() const { return m_recovery; }
    PointerPatchProxy operator[](FF_FieldKey key) const;
    PointerPatchProxy operator[](std::string_view key_name) const;
    inline PointerPatchProxy operator[](const char* key_name) const {
        return operator[](std::string_view(key_name));
    }
};
class AdvancedBuilderAccess;

// =====================================================================
// BUILDER
// =====================================================================
/**
 * @brief Builder class for constructing FastFHIR binary streams in a concurrent, lock-free manner.
 * 
 * The Builder manages a large virtual memory arena and allows multiple threads to append data concurrently.
 * It provides thread-safe methods for appending data, setting the root resource, and finalizing the stream with a checksum.
 * The Builder also includes proxy classes for safely patching pointers and array entries in an active concurrent context.
 * 
 */
class Builder {
    friend class FastFHIR::AdvancedBuilderAccess;
    friend class FastFHIR::PointerPatchProxy;  
    BYTE* m_base;
    size_t              m_capacity;
    std::atomic<Offset> m_stream_head;
    Offset              m_checksum_offset;
    Offset              m_root_offset;
    RECOVERY_TAG        m_root_recovery;
    uint32_t            m_version;
    std::atomic<bool>   m_finalizing;
    std::atomic<uint64_t> m_active_mutators;

    bool try_begin_mutation();
    void end_mutation();

public:
    Builder(const Builder&) = delete;
    Builder& operator=(const Builder&) = delete;
    Builder(Builder&&) = delete;
    Builder& operator=(Builder&&) = delete;

    /**
     * @brief Reserves a massive Virtual Address Space without consuming physical RAM.
     */
    Builder(size_t size_hint = 0, size_t virtual_capacity = 2ULL * 1024 * 1024 * 1024, uint32_t version = FHIR_VERSION_R5);
    ~Builder();

    // --- Core Stream Access ---
    
    const BYTE* data() const { return m_base; }
    Size total_written() const { return m_stream_head.load(std::memory_order_relaxed); }

    // --- Lock-Free Concurrent Appending ---

    /**
     * @brief The core concurrent ingestion method. Cleaned up to use TypeTraits.
     */
    template<typename T_Data>
    Offset append(const T_Data& data) {
        if (!try_begin_mutation()) {
            throw std::runtime_error("FastFHIR: Builder is finalizing; append is no longer allowed.");
        }

        struct MutationGuard {
            Builder* self;
            ~MutationGuard() { self->end_mutation(); }
        } guard{this};

        // Automatically resolved via ffc.py generated traits
        Size exact_size = TypeTraits<T_Data>::size(data, m_version);
        
        Offset start = m_stream_head.fetch_add(exact_size, std::memory_order_relaxed);
        
        if (start + exact_size > m_capacity) {
            throw std::runtime_error("FastFHIR: Exceeded maximum virtual arena capacity.");
        }
        
        TypeTraits<T_Data>::store(m_base, start, data, m_version);
        
        return start;
    }

    /**
     * @brief Appends data to the stream and returns a thread-safe handle for [] assignments.
     */
    template<typename T_Data>
    ObjectHandle append_obj(const T_Data& data) {
        return ObjectHandle(this, append(data), TypeTraits<T_Data>::recovery);
    }

    /**
     * @brief Instantiates a read-only Node directly from a known offset mid-stream.
     */
    Node view_node(Offset offset, RECOVERY_TAG recovery, FF_FieldKind kind = FF_FIELD_BLOCK) const;

    /**
     * @brief Low-level mutable access to a V-Table pointer for amending data.
     */
    void amend_pointer(Offset object_offset, size_t field_vtable_offset, Offset new_target_offset);

    // --- Finalization & Checksums ---

    /** 
     * @brief Sets the root resource pointer and recovery tag in the header. 
     * [NOTE] This function must be called before finalize().
     */
    void set_root(const ObjectHandle& handle);
    
    using HashCallback = std::function<std::vector<BYTE>(const unsigned char* byte_start, Size bytes_to_hash)>;
    /**
     * @brief Bakes the File Header, and executes the provided hashing callback to seal the file.
     * @param algo The cryptographic algorithm tag to write into the metadata.
     * @param hasher A callback that takes the payload and returns the raw hash bytes.
     * @return A view of the complete, sealed file (including the checksum footer) ready for network transmission.
     */
    std::string_view finalize(FF_Checksum_Algorithm algo = FF_CHECKSUM_NONE, const HashCallback& hasher = nullptr);

    protected:
    Offset allocate_raw(Size size);
    FF_Result write_offset_at(Offset target_addr, Offset child_offset);
};

/**
 * @brief AdvancedBuilderAccess provides low-level, unsafe access to the Builder's internal methods for expert use cases.
 * 
 * This class is intentionally not documented in detail, as its methods are unsafe and meant for advanced users who 
 * understand the internal workings of the Builder. Use with caution, as improper use can lead to data corruption 
 * or invalid FastFHIR streams.
 * 
 */
class AdvancedBuilderAccess {
    Builder*const m_builder;
public:
    AdvancedBuilderAccess(Builder& builder) : m_builder(&builder) {}
    AdvancedBuilderAccess() = delete;
    AdvancedBuilderAccess(const AdvancedBuilderAccess&) = delete;
    AdvancedBuilderAccess& operator=(const AdvancedBuilderAccess&) = delete;
    AdvancedBuilderAccess(AdvancedBuilderAccess&&) = delete;
    AdvancedBuilderAccess& operator=(AdvancedBuilderAccess&&) = delete;

    /**
     * @brief Unsafely allocates raw memory within the builder's arena.
     * 
     * @param size The size of the memory to allocate.
     * @return Offset The offset of the allocated memory within the builder's arena.
     */
    Offset UNSAFE_allocate_raw(Size size) {
        return m_builder ? m_builder->allocate_raw(size) : FF_NULL_OFFSET;
    }

    /**
    * @brief Unsafely writes an offset directly (non-atomically) within the builder's arena.
    * 
    * @param target_addr The address of the target offset to write.
    * @param child_offset The new offset value to write.
    */
    FF_Result UNSAFE_write_offset_at(Offset target_addr, Offset child_offset) {
        return m_builder ? m_builder->write_offset_at(target_addr, child_offset) : 
        FF_Result{FF_FAILURE,"AdvancedBuilderAccess: Builder instance is null."};
    }
};

// =====================================================================
// INLINE TEMPLATE IMPLEMENTATIONS
// =====================================================================
inline PointerPatchProxy& PointerPatchProxy::operator=(const ObjectHandle& child) {
    // --- STRICT SCHEMA VALIDATION ---
    if (m_ref.target_recovery == RECOVER_FF_RESOURCE) {
        // Polymorphic field: Ensure the child is actually a top-level Resource
        if (!FF_IsResourceTag(child.recovery())) 
            throw std::invalid_argument("FastFHIR Schema Violation: Expected a top-level Resource (0x0200 range), but received a different block type.");
    } else if (child.recovery() != m_ref.target_recovery) 
        // Strictly typed field: Ensure an exact match
        throw std::invalid_argument("FastFHIR Schema Violation: Attempted to assign an incompatible type.");

    m_builder->amend_pointer(m_ref.object_offset, m_ref.field_vtable_offset, child.offset());
    return *this;
}

template <typename T_Data>
Offset PointerPatchProxy::operator=(const T_Data& data) {
    // --- STRICT SCHEMA VALIDATION ---
    RECOVERY_TAG child_tag = TypeTraits<T_Data>::recovery;
    if (m_ref.target_recovery == RECOVER_FF_RESOURCE) {
        // Polymorphic field: Ensure the child is actually a top-level Resource
        if (!FF_IsResourceTag(child_tag)) 
            throw std::invalid_argument("FastFHIR Schema Violation: Expected a top-level Resource (0x0200 range), but received a different block type.");
    } else if (child_tag != m_ref.target_recovery) {
        throw std::invalid_argument("FastFHIR Schema Violation: Attempted to append an incompatible type to a strictly typed field.");
    }

    // 1. Thread-safe append of the child data
    Offset child_offset = m_builder->append(data);
    
    // 2. Thread-safe pointer patch on the parent V-Table
    m_builder->amend_pointer(m_ref.object_offset, m_ref.field_vtable_offset, child_offset);
    
    return child_offset;
}

inline PointerPatchProxy ObjectHandle::operator[](FF_FieldKey key) const {
    if (m_offset == FF_NULL_OFFSET) 
        throw std::runtime_error("FastFHIR: Invalid ObjectHandle; cannot assign field '" + 
                                 std::string(key.name) + "' on a null/unallocated object.");
    else if (key.kind != FF_FIELD_BLOCK && key.kind != FF_FIELD_ARRAY && key.kind != FF_FIELD_STRING) 
        throw std::runtime_error("FastFHIR: Field '" + std::string(key.name) + 
                                 "' is not a pointer-backed field. PointerPatchProxy only supports BLOCK/ARRAY/STRING.");
    
    // Assuming FF_FieldKey generated by ffc.py contains the direct field offset
    return PointerPatchProxy(m_builder, PointerRef{m_offset, key.field_offset, key.child_recovery}); 
}

} // namespace FastFHIR
